[package]
authors = ["Casey Primozic <me@ameo.link>"]
name = "project-hoster-server"
version = "0.1.0"

[dependencies]
actix = "0.7"
actix-web = "0.7"
diesel = { version = "1.3.2", features = ["mysql", "r2d2"] }
dotenv = "0.13.0"
r2d2 = "0.8.2"
