# Generated by Django 2.1.1 on 2018-09-11 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('serversite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentversion',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staticdeployment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staticdeployment',
            name='subdomain',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
