# Generated by Django 2.1.1 on 2019-06-18 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('serversite', '0004_staticdeployment_not_found_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subdomain', models.SlugField(max_length=255, unique=True)),
                ('use_cors_headers', models.BooleanField(default=True)),
                ('destination_address', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
